"on":
  push:
    branches:
    - master
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Set Github tag
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Update Porter App
      timeout-minutes: 20
      uses: lsnow99/porter-update-action@v0.4.0
      with:
        app: fdjkls
        build_secrets: PORTERSECRET_1=${{ secrets.PORTERSECRET_PORTERSECRET_1 }},PORTERSECRET_2=${{
          secrets.PORTERSECRET_PORTERSECRET_2 }}
        cluster: "1"
        host: https://6180-160-72-72-58.ngrok.io
        namespace: default
        project: "1"
        tag: ${{ steps.vars.outputs.sha_short }}
        token: ${{ secrets.PORTER_TOKEN_1 }}
